services:
  db:
    image: mariadb:10.11
    container_name: buchhaltung-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - /srv/docker/buchhaltung/data/db:/var/lib/mysql
      - /srv/docker/buchhaltung/app/my.cnf:/etc/mysql/my.cnf

  app:
    build: .
    container_name: buchhaltung-app
    restart: always
    environment:
      MARIADB_HOST: db
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_FROM_EMAIL: ${SMTP_FROM_EMAIL}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
    depends_on:
      - db
    volumes:
      - /srv/docker/buchhaltung/data/htdocs:/var/www/html
      - buchhaltung-vendor:/var/www/html/vendor
      - ./php.ini:/usr/local/etc/php/php.ini
      - /srv/docker/buchhaltung/data/backup:/srv/backup
    ports:
      - "28700:80"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: buchhaltung-phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: https://buhadb.nik0.internal/
    ports:
      - "28701:80"

  pdfocr:
    image: python:slim
    container_name: buchhaltung-ocr
    working_dir: /app
    volumes:
      - /srv/docker/buchhaltung/ocr:/app
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y tesseract-ocr tesseract-ocr-deu poppler-utils &&
      pip install --upgrade pip &&
      pip install pdf2image pytesseract pillow flask &&
      python app.py
      "
    ports:
      - "6600:6600"
    restart: unless-stopped
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/

volumes:
  buchhaltung-vendor:
